skalenetwork/portal

env/mainnet/chainsData.json
Adding correct USDC on Nebula to chainData config to show it on bridge UI
=> Add USDC to Nebula

README.md, env/mainnet/chainsData.json, env/mainnet/metaportConfig.json
Add DAI and USDT to Calypso (Eth -> Calypso, Europa -> Calypso, Calypso -> Europa, Calypso -> Eth)
Add USDT and WBTC to Nebula (Eth -> Nebula, Europa -> Nebula, Nebula -> Europa, Nebula -> Eth)
Add USDC and USDT pair (Calypso -> Nebula, Nebula -> Calypso)
=> Add stablecoins

config/mainnet.ts
Added token pairs for ETH:
- Europa <-> Nebula
- Nebula <-> Mainnet 
- Nebula <-> Calypso
=> Add mainnet token pairs - Europa ETH

config/testnet.ts
Only testnet metaport config changes, no code changed.
=> Add TRBP token on testnet

config/testnet.ts
Closes #229 
Closes #246 
Closes #247 
Closes #250
=> config(Tokens): Update Token Config

config/mainnet.ts
In this PR:
- Additional token mappings
- Updated submodules
=> Update token mappings, update submodules

config/mainnet.ts
- Add compass token to SKALE Portal Config
- Confirmed, this is fully tested
=> config(Token): Add Compass Token (CMPS)

config/mainnet.ts
- Adds Exorde Token Mapping on Europa
=> Add Exorde Token Mappings to Portal

src/components/AppChains.tsx, src/components/SchainDetails.tsx, src/components/chains/HubTile.tsx, src/components/delegation/RetrieveRewardModal.tsx, src/pages/Bridge.tsx, src/pages/Chains.tsx
This PR includes fixes for multiple minor bugs found in Portal 2.3
=> Fix portal 2.3 bugs

src/pages/Ecosystem.tsx
In this PR:
- Add button with link to App metadata submission form
=> Add Submit Your Project button to ecosystem page

config/mainnet.ts
- Add USDC on Titan
- Add Routes between Mainnet, Europa, Titan, Calypso, Nebula for USDC
Resolves #367
=> Add USDC Mappings and Titan Routes

config/mainnet.ts
Adds token mapping for RAZOR from Ethereum Mainnet <--> Europa Mainnet Hub
=> Config: Add RAZOR Token Mapping

src/AuthContext.tsx, src/pages/Ecosystem.tsx
In this PR:
- Updated sign-in message
- Updated sign-in flow: automatic sign-in request removed from the auth context
=> Update sign-in hook, update sign-in message

src/AuthContext.tsx
In this PR:
- Hotfix for sign-in requests in the `AuthContext` - removed address change handler
=> Hotfix for sign-in in AuthContext

packages/core/src/types/ChainsMetadata.ts, src/components/ecosystem/AppCardV2.tsx, src/components/profile/ProfileModal.tsx, src/core/metadata.ts, src/pages/App.tsx
In this PR:
- Updated Pre-TGE logic: added `from` and `to` timestamps for Pre-TGE apps
=> Update pre-tge logic, update core lib

src/Router.tsx, src/components/GetSFuel.tsx, src/pages/App.tsx, src/pages/Ecosystem.tsx, src/useSFuel.tsx
In this PR:
- Updated logic in `usesFuel` hook
- Added state type for `usesFuel` state
- Added `loading` state for sFUEL station
- Added percentage completion for sFUEL mining
- Handled address changes
=> Fix sFUEL status checks, add sFUEL completion percentage

config/testnet.ts
In this PR:
- Updated SKIVVY token metadata on testnet
=> Update SKIVVY token metadata

src/components/profile/ProfileModal.tsx, src/components/profile/ProfileModalActions.tsx, src/components/profile/ProfileModalHeader.tsx, src/pages/App.tsx, src/pages/Ecosystem.tsx, src/pages/Home.tsx
In this PR:
- Removed all Swell messages
- Removed email functionality from Profile
- Minor UI changes
- Updated submodules
=> Hide email section, remove Swell messages, update submodules

generate-imports.cjs, src/components/ChainLogo.tsx
In this PR:
- Minor fix for chain/app logos with numbers in the name
=> Add fix for images with numbers in name

config/mainnet.ts
In this PR:
- Updated icons for RUBY and USDP
- Changed tokens order for mainnet and Europa
No code or token mappings changed.
=> Update tokens list in mainnet config

src/core/chain.ts
- Wrap getChainId with useQuantity to strip leading non 0x zeroes
=> Fix getChainId -> JSON RPC Error in Metamask (During Add Chain)

config/mainnet.ts
In this PR:
- Remove RAZOR token from Bridge config
- Remove Razor chain from Bridge config
=> Update mainnet.ts - remove RAZOR token from config

config/mainnet/europa.ts, config/mainnet/index.ts, config/mainnet/mainnet.ts, packages/core/src/metadata/faucet.json, src/useSFuel.tsx
In this PR:
- Updated RAZOR token config
- Removed Razor chain from faucet
=> Update RAZOR token configuraton

packages/metaport/src/core/actions/erc20.ts
In this PR:
- Fixed an issue with `approve` function in ERC20 S2S transfer
=> Fix approve function for erc20 s2s transfers

src/data/changelog.mdx
**What’s in this PR?**
This PR updates the changelog to include entries for previous major releases: v4.0, v3.2, v3.1, and v3.0. This helps provide better historical context and visibility into the evolution of the Portal.
**🔄 Changelog Additions**
**v4.0**
- 🛠️ Portal becomes the core repo
- ⚙️ Separate build configs per package
- 🚀 Faster CI/CD & optimized maintenance workflows
**v3.2**
- 🧑🏻‍💻 New Delegations Page for Validators
-💰 Claim Paymaster Rewards
- ➕ MAX Button added in Bridging
**v3.1**
- 📈 Trending dApps section added
- 🧠 Recommended dApps algorithm introduced
- 📧 Email field added to user profiles
- 🖼️ Screenshots section for dApps
- 🔋 “Get sFUEL” Button added for convenience
**v3.0**
- 🎨 Redesigned Portal UI
- 📱 New Ecosystem page
- 🎮 App Detail Pages
- 📊 Improved Metrics …
=> Changelog for all the other releases

index.html, src/App.scss
In this small PR, the Font on CTA Banner was changed to Inter Extra Bold
=> Font banner changed to inter

packages/metaport/src/components/BridgeChainCard.tsx, packages/metaport/src/styles/styles.module.scss
Previous:
The height of the "Calypso Hub", "Destination Chain", and "Source Chain" elements is different from the other chain elements.
Now:
The height of all elements are the same.
=>  Different elements height fixed on the chain selection pop-up
