src/App.scss
src/Router.tsx
src/components/ChainAccordion.tsx
src/components/CopySurface.tsx
src/components/MonthSelector.tsx
src/components/PricingInfo.tsx
src/components/SchainDetails.tsx
src/components/SkStack.tsx
src/components/Tile.tsx
src/core/paymaster.ts
src/core/timeHelper.ts
src/data/paymaster.ts
src/pages/Admin.tsx
src/pages/Schain.tsx

This PR adds pricing launch timestamp for chain pricing functionality. 
Timestamp can be configured for each network individually in `src/data/paymaster.ts`.
PR also includes minor CSS changes.
No additional tests added.
Timestamp functionality could be tested manually by setting timestamp in seconds for the corresponding network.
Resolves #118

Add pricing launch timestamp

---

config/mainnet.ts
config/staging.ts

This PR adds new token pairs for Chaos Testnet and fixes WBTC decimals amount (config changes only)
No code changed.
Resolves https://github.com/skalenetwork/portal/issues/166
Resolves https://github.com/skalenetwork/portal/issues/167
Resolves https://github.com/skalenetwork/portal/issues/168

Update staging and mainnet tokens data

---

config/mainnet.ts

This adds WBTC to the Calypso route. 
Routing is available via Ethereum and Europa.

Add WBTC to Calypso Route

---

src/App.scss
src/_variables.scss
src/components/Message.tsx
src/components/Tile.tsx
src/components/delegation/Delegations.tsx
src/components/delegation/DelegationsToValidator.tsx
src/components/delegation/RetrieveRewardModal.tsx
src/components/delegation/Reward.tsx
src/pages/Staking.tsx

This PR adds an ability to retrieve staking rewards to the custom address. 
By default, connect wallet address is pre-filled, user can modify the address. 
Modified address saved for the currently open tab.
Rewards retrieval to custom address tested to testnet network.
No unit tests added, no performance changes.

Add custom wallet support for staking rewards

---

src/App.scss
src/components/SchainDetails.tsx
src/components/chains/tabs/Tokens.tsx
src/pages/Chains.tsx

This PR:
- Adds ETH clones to Tokens tab on Chain details page
- Fixes error with "Connect to Chain" by adding block explorer URL

Add ETH to Tokens tab, fix connect to chain

---

src/App.scss
src/AuthContext.tsx
src/Portal.tsx
src/components/AccountMenu.tsx
src/components/ConnectWallet.tsx
src/components/Message.tsx
src/components/Tile.tsx
src/components/delegation/RetrieveRewardModal.tsx
src/components/profile/EmailSection.tsx
src/components/profile/ProfileModal.tsx
src/components/profile/ProfileModalActions.tsx
src/components/profile/ProfileModalHeader.tsx
src/components/profile/SwellMessage.tsx
src/pages/Ecosystem.tsx
src/pages/Home.tsx
src/styles/ProfileModal.scss
src/styles/components.scss

In this PR:
- Added user profile
- Added email field to profile
- Updated auth context to include email-related API calls
- Other minor fixes

Add user profile, add email getter and setter, other minor changes

---

src/Router.tsx
src/components/ExternalRedirect.tsx
src/components/ecosystem/AppCardV2.tsx
src/components/profile/ProfileModal.tsx
src/core/meta.ts
src/pages/App.tsx
src/pages/Ecosystem.tsx

In this PR:
- Update tooltip text on all main pages
- Hide the most liked tab and badges 
- Add redirect for app submission

Update tooltip, hide most liked tab, add redirect

---

src/SkDrawer.tsx
src/core/constants.ts

In this PR:
- Added link to Get Started page

Add Get Started URL

---

README.md
config/testnet.ts

In this PR:
- Updated README:
- Bridge params usage fixed 
- Updated required and optional env variables
- Added build shortcuts
- Added default endpoint in testnet config

Update README - usage, dev setup

---

config/mainnet.ts
src/pages/Validator.tsx
src/pages/Validators.tsx

In this PR:
- `Manage Validator` page was renamed to `Validator Operations`

Update Validator management page name

---

src/components/ecosystem/RecommendedApps.tsx
src/components/ecosystem/UserRecommendations.tsx
src/pages/App.tsx

**Problem:**
The “Featured” label wasn’t displayed consistently. It appeared on dApp cards on the Ecosystem homepage but was missing from individual dApp detail pages.
**This PR fixes that by:**
Ensuring the “Featured” label is now consistently shown on the dApp detail page (in the header) and in the “Discover More” section, matching its appearance on the Ecosystem main page.

Fixed bug with featured dApps

---

config/mainnet/index.ts

This pull request makes a small change to the `METAPORT_CONFIG` in `config/mainnet/index.ts`. Specifically, it comments out two entries (`wan-red-ain` and `adorable-quaint-bellatrix`) in the `chains` array, effectively disabling them while keeping their references for potential future use.

Comment out old chains in mainnet metaport config

---

packages/metaport/src/components/TokenList.tsx

This PR fixes a UI bug where the token search input is not cleared after closing the token selection modal. Previously, when a user searched for a token (e.g., “SKALE”) and selected it, the search term would persist even after reopening the modal, potentially on a different chain, causing the list to remain filtered.
**Code changes:**
const handleOpen = () => setOpen(true)
const handleClose = () => {
setOpen(false)
setSearchQuery('')
}
**Result:**
- The search input is now reset every time the modal closes.
- Users always see an unfiltered list when reopening the modal.

Cleared token search input on modal close

---

src/components/ecosystem/tabs/FavoriteApps.tsx
src/components/ecosystem/tabs/FeaturedApps.tsx
src/components/ecosystem/tabs/MostLiked.tsx
src/components/ecosystem/tabs/NewApps.tsx
src/components/ecosystem/tabs/TrendingApps.tsx
src/pages/Ecosystem.tsx

Previously, only the All tab on the Ecosystem page displayed the “🚫 No … apps match your current filters” message when no search results were found. Also, in 4.0 the favorites tab filter wasn't working, and this PR fixed it.
**Version:**
Portal 4.1.0 Beta 1.0
This PR fixes that behavior for UI consistency.
The message "🚫 No ... apps match your current filters" now appears across all relevant tabs:
•	All
•	Featured
•	New
•	Trending
•	Favorites

Emoji didn't appeared on All Tabs When Filtering dApps and favorite filter didn't worked

---

src/components/ecosystem/tabs/FavoriteApps.tsx
src/components/ecosystem/tabs/FeaturedApps.tsx
src/components/ecosystem/tabs/MostLiked.tsx
src/components/ecosystem/tabs/NewApps.tsx
src/components/ecosystem/tabs/TrendingApps.tsx
src/data/changelog.mdx

This PR includes two small fixes:
✅ Fixed the broken link for Homepage Improvements in the 4.1 Release changelog.
✅ Adjusted the text size for the "No ... apps match your current filters" message on the Homepage, ensuring consistent text size across all tabs when no filtered dApps are found.

Fixed changelog link on Homepage Improvements (4.1)

---

src/pages/Bridge.tsx

In this small PR, we updated the Testnet Bridge Maintenance Notice until the end of this week (July 18th).

Data for Testnet Bridge Maintenance Notice updated

---

config/legacy/europa.ts
config/legacy/index.ts
config/legacy/nebula.ts
packages/core/src/contracts.ts
packages/core/src/endpoints.ts
packages/core/src/metadata/faucet.json
packages/metaport/src/core/network.ts

In this pull request, Karina, Vadim, and I configured the new Legacy network (#613) for Hoodi, replacing Holesky.
We added the new chains in all relevant places and updated the contract addresses accordingly.
We also added the Allocator and Paymaster contracts.

Setup: Legacy network #613 for Hoodi instead of Holesky

---

package.json
src/components/ecosystem/tabs/FavoriteApps.tsx
src/pages/Ecosystem.tsx

In this PR, we fixed the Favorites tab layout #626 
On the Favorites tab, the project cards were stretched and displayed in a single long column instead of being arranged in neat rows, meaning the grid wasn’t working correctly. We fixed this by applying the same grid layout used on the other tabs.

Fixed favorites gird #626 

---

package.json
src/pages/Ecosystem.tsx

In this PR, we fixed the following issue (#624):
After applying a category filter, the top row of dApps was partially cut off from view. The newly added filter tag pushed the content grid down, making the top results not fully visible even when the page was scrolled to the top.
Now, after applying a filter, the layout no longer shifts. The checked items logic was added to the handleScroll function so the top row of dApps always remains fully visible after the results are updated.
We also added the build:qa script to the package.json file to allow checking the QA network during the development stage in the future.

Fixed the bug  "Settings Filtering by category cuts off the top row of dApps" - #624

---

package.json

This PR fixes the version inconsistency introduced in the previous 4.2.0 PRs by updating the version number in the package .json file:
- Changed 4.1.0 to 4.2.0 to match the current release for QA to be able to test it with the new version. #632

Version name changed to 4.2.0 - #632
